import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

import pytest
from datetime import datetime
from unittest.mock import MagicMock
import mongomock
import BackEnd.GlobalInfo.ResponseMessages as ResponseMessage
from BackEnd.Functions.projectFunctions import fnPostProject

# Mock de base de datos
from BackEnd.GlobalInfo.Helpers import dbConnection
dbConnection.clProjects = mongomock.MongoClient().db.collection

@pytest.fixture
def sample_data():
    return {
        "name": "Proyecto Integrador",
        "identifier": "PI-2025",
        "startDate": "2025-02-01",
        "description": "Proyecto académico basado en OpenUP",
        "responsible": "Juan Pérez",
        "tags": ["educación", "flask", "angular"],
        "phases": ["Incepción", "Elaboración", "Construcción", "Transición"]
    }


def test_create_project_success(sample_data):
    result = fnPostProject(**sample_data)

    assert result["status"] == ResponseMessage.message200
    assert result["project"]["name"] == sample_data["name"]
    assert len(result["project"]["phases"]) == 4
    assert result["project"]["status"] == "Creado"

def test_prevent_duplicate_project(sample_data):
    # Insertar proyecto inicial
    fnPostProject(**sample_data)

    # Intentar insertar duplicado
    result = fnPostProject(**sample_data)
    
    assert result == ResponseMessage.message409

def test_phases_autogenerated(sample_data):
    result = fnPostProject(**sample_data)
    
    assert "phases" in result["project"]
    assert result["project"]["phases"][0]["name"] == "Incepción"
    assert result["project"]["phases"][3]["name"] == "Transición"
    assert all(phase["status"] == "Pendiente" for phase in result["project"]["phases"])
